# Generated by Django 6.1.1 on 2026-09-29 13:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('lectures', '0001_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True, help_text='Personal notes typed by student')),
                ('storage_key', models.CharField(blank=True, help_text='Storage key for uploaded note document', max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('video_timestamp_seconds', models.PositiveIntegerField(default=0, help_text='Timestamp in video when note was captured')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='courses.course')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='lectures.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Note',
                'verbose_name_plural': 'Student Notes',
                'ordering': ['video_timestamp_seconds', '-created_at'],
                'indexes': [models.Index(fields=['user', 'lecture'], name='progress_st_user_id_c735be_idx'), models.Index(fields=['user', 'course'], name='progress_st_user_id_60df4d_idx')],
            },
        ),
    ]
