# Generated by Django 6.1.1 on 2026-09-29 12:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('access_type', models.CharField(choices=[('lifetime', 'Lifetime Access'), ('fixed_duration', 'Fixed Duration'), ('subscription', 'Subscription')], default='lifetime', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course')),
                ('order', models.ForeignKey(blank=True, help_text='Order that created this enrollment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='enrollments_user_id_963010_idx'), models.Index(fields=['course', 'status'], name='enrollments_course__f8877c_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
