# Generated by Django 6.1.1 on 2026-09-29 12:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('completed_at', models.DateTimeField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('storage_key', models.CharField(blank=True, help_text='PDF in object storage', max_length=500)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
