# Generated by Django 6.1.1 on 2026-09-29 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couponredemption',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'is_active'], name='coupons_cou_code_1aa9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'user'], name='coupons_cou_coupon__5ef611_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='couponredemption',
            unique_together={('coupon', 'order')},
        ),
    ]
