# Generated by Django 6.1.1 on 2026-09-29 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('user_suspended', 'User Suspended'), ('user_activated', 'User Activated'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('password_reset', 'Password Reset'), ('email_verified', 'Email Verified'), ('course_created', 'Course Created'), ('course_published', 'Course Published'), ('course_unpublished', 'Course Unpublished'), ('course_deleted', 'Course Deleted'), ('lecture_uploaded', 'Lecture Uploaded'), ('price_changed', 'Price Changed'), ('order_created', 'Order Created'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('refund_issued', 'Refund Issued'), ('enrollment_created', 'Enrollment Created'), ('enrollment_revoked', 'Enrollment Revoked'), ('coupon_created', 'Coupon Created'), ('role_changed', 'Role Changed'), ('settings_changed', 'Settings Changed'), ('file_uploaded', 'File Uploaded')], max_length=50)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'action'], name='audit_audit_actor_i_aad064_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
    ]
