# Generated by Django 6.1.1 on 2026-09-29 12:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_free_preview', models.BooleanField(default=False, help_text='If true, unenrolled students can view this lecture.')),
                ('is_published', models.BooleanField(default=False)),
                ('estimated_duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lectures.lecture')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('note_type', models.CharField(choices=[('html', 'HTML/Text'), ('markdown', 'Markdown'), ('pdf', 'PDF File'), ('docx', 'Word Document'), ('other', 'Other File')], default='html', max_length=20)),
                ('html_content', models.TextField(blank=True, help_text='For inline HTML/Markdown notes')),
                ('storage_key', models.CharField(blank=True, help_text='For file-based notes stored in object storage.', max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lectures.lecture')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LectureVideo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(help_text='Key (path) in object storage bucket — NOT a public URL.', max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(default='video/mp4', max_length=100)),
                ('is_processed', models.BooleanField(default=True)),
                ('thumbnail_key', models.CharField(blank=True, max_length=500)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='lectures.lecture')),
            ],
            options={
                'verbose_name': 'Lecture Video',
            },
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['section', 'order'], name='lectures_le_section_255e09_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['is_published'], name='lectures_le_is_publ_510292_idx'),
        ),
    ]
